# version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: iam_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  backend:
    build: ./backend
    container_name: iam_backend
    ports:
      - "8000:8000"
    environment:
      - MONGO_URL=mongodb://mongodb:27017
      - SECRET_KEY=supersecretkey-change-in-prod
      - ALGORITHM=HS256
      - GROQ_API_KEY=${GROQ_API_KEY}
      - VPN_SERVER_URL=http://vpn-server:8000
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    container_name: iam_frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

  vpn-server:
    build: ./vpn/vpn-server
    container_name: iam_vpn_server
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    ports:
      - "4000:4000"
      - "1194:1194/udp"
    networks:
      default:
      lab_network:
        ipv4_address: 125.10.0.2
    volumes:
      - vpn_master_data:/etc/openvpn

  dev-server:
    build: ./vpn/dev-server
    container_name: dev-server
    networks:
      lab_network:
        ipv4_address: 125.10.0.10
    cap_add:
      - NET_ADMIN

networks:
  default:
  lab_network:
    ipam:
      config:
        - subnet: 125.10.0.0/24

volumes:
  mongodb_data:
  vpn_master_data:
