# version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: iam_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

    networks:
      - default

  backend:
    build: ./backend
    container_name: iam_backend
    ports:
      - "8000:8000"
    environment:
      - MONGO_URL=mongodb://mongodb:27017
      - DATABASE_NAME=iam_db
      - SECRET_KEY=supersecretkey
      - ALGORITHM=HS256
      - GROQ_API_KEY=${GROQ_API_KEY}
      - VPN_SERVER_URL=http://vpn-server:4000
      - GITLAB_URL=http://gitlab.eng.vpn
      - GITLAB_ADMIN_TOKEN=${GITLAB_ADMIN_TOKEN:-}
      - GITLAB_SYNC_ENABLED=true
    depends_on:
      - mongodb
    volumes:
      - backend_data:/src/data
      - ./backend:/src
    extra_hosts:
      - "gitlab.eng.vpn:172.30.0.50"
    networks:
      default:
      iam_private:

  frontend:
    build: ./frontend
    container_name: iam_frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - default

  vpn-server:
    build: ./vpn/vpn-server
    container_name: iam_vpn_server
    environment:
      - VPN_SERVER_IP=${VPN_SERVER_IP:-10.35.156.201}
      - MONGO_URL=mongodb://mongodb:27017
      - DATABASE_NAME=iam_db
    depends_on:
      - mongodb
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    ports:
      - "4000:4000"
      - "1194:1194/udp"
    volumes:
      - vpn_master_data:/etc/openvpn
    networks:
      default:
      iam_private:

  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: iam_gitlab
    hostname: gitlab.eng.vpn
    restart: unless-stopped
    shm_size: "256m"
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.eng.vpn'
        gitlab_rails['gitlab_shell_ssh_port'] = 22
    volumes:
      - gitlab_config:/etc/gitlab
      - gitlab_logs:/var/log/gitlab
      - gitlab_data:/var/opt/gitlab
    networks:
      iam_private:
        ipv4_address: 172.30.0.50

networks:
  default:
  iam_private:
    ipam:
      config:
        - subnet: 172.30.0.0/24

volumes:
  mongodb_data:
  vpn_master_data:
  backend_data:
  gitlab_config:
  gitlab_logs:
  gitlab_data:
