# version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: iam_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - default

  backend:
    build: ./backend
    container_name: iam_backend
    ports:
      - "8000:8000"
    environment:
      - MONGO_URL=mongodb://mongodb:27017
      - DATABASE_NAME=iam_db
      - SECRET_KEY=supersecretkey
      - ALGORITHM=HS256
      - GROQ_API_KEY=${GROQ_API_KEY}
      - VPN_SERVER_URL=http://vpn-server:4000
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
    networks:
      - default

  frontend:
    build: ./frontend
    container_name: iam_frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - default

  vpn-server:
    build: ./vpn/vpn-server
    container_name: iam_vpn_server
    environment:
      - VPN_SERVER_IP=${VPN_SERVER_IP:-10.35.156.201}
      - MONGO_URL=mongodb://mongodb:27017
      - DATABASE_NAME=iam_db
    depends_on:
      - mongodb
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    ports:
      - "4000:4000"
      - "1194:1194/udp"
    volumes:
      - vpn_master_data:/etc/openvpn
    networks:
      - default

networks:
  default:

volumes:
  mongodb_data:
  vpn_master_data: