port 1194
proto udp
dev tun
ca /etc/openvpn/easy-rsa/pki/ca.crt
cert /etc/openvpn/easy-rsa/pki/issued/server.crt
key /etc/openvpn/easy-rsa/pki/private/server.key
dh /etc/openvpn/easy-rsa/pki/dh.pem
crl-verify /etc/openvpn/crl.pem

management 127.0.0.1 7505

client-config-dir /etc/openvpn/ccd

# push "route 125.20.0.0 255.255.255.0"
# push "route 125.21.0.0 255.255.255.0"
# push "route 125.22.0.0 255.255.255.0"
# push "route 125.23.0.0 255.255.255.0"


topology subnet
server 100.64.0.0 255.255.0.0

script-security 2
client-connect "/app/client-connect.sh"
client-disconnect "/app/client-disconnect.sh"

keepalive 10 60
persist-key
persist-tun
status /var/log/openvpn/status.log
status-version 3
verb 3
